# Generated by Django 4.0.1 on 2022-01-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('title', models.CharField(default='NULL', max_length=512)),
                ('description', models.CharField(default='NULL', max_length=512)),
                ('privacy', models.CharField(default='NULL', max_length=512)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('userid2', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('userid2', models.CharField(default='NULL', max_length=120)),
                ('type', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('userid2', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('title', models.CharField(default='NULL', max_length=512)),
                ('description', models.CharField(default='NULL', max_length=512)),
                ('privacy', models.CharField(default='NULL', max_length=512)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('type', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('groupid', models.CharField(default='NULL', max_length=120)),
                ('eventid', models.CharField(default='NULL', max_length=120)),
                ('privacy', models.CharField(default='NULL', max_length=120)),
                ('text', models.CharField(default='NULL', max_length=512)),
                ('image', models.CharField(default='NULL', max_length=512)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='NULL', max_length=120)),
                ('password', models.CharField(default='NULL', max_length=512)),
                ('contact', models.CharField(default='NULL', max_length=512)),
                ('firstname', models.CharField(default='NULL', max_length=512)),
                ('lastname', models.CharField(default='NULL', max_length=512)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='NULL', max_length=120)),
                ('groupid', models.CharField(default='NULL', max_length=512)),
                ('time', models.CharField(default='NULL', max_length=512)),
            ],
        ),
    ]
