# Generated by Django 4.0.1 on 2022-01-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RenameModel(
            old_name='FriendRequests',
            new_name='FriendRequest',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupRequests',
            new_name='GroupRequest',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='UsersInGroups',
            new_name='UsersInGroup',
        ),
    ]
