# Generated by Django 4.0.1 on 2022-01-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_groups_event_rename_friends_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
