# Generated by Django 4.0.1 on 2022-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_event_userid_alter_grouprequest_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
