# Generated by Django 4.0.1 on 2022-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCookie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(default='', max_length=512, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
