# Generated by Django 4.0.1 on 2022-01-31 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_logincookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='userid2',
            field=models.CharField(default='NULL', max_length=512),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='userid2',
            field=models.CharField(default='NULL', max_length=512),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='userid2',
            field=models.CharField(default='NULL', max_length=512),
        ),
        migrations.AlterField(
            model_name='login',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
        migrations.AlterField(
            model_name='usersingroup',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersingroup',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
    ]
