# Generated by Django 4.0.1 on 2022-01-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_event_time_alter_friend_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='NULL', max_length=512)),
                ('time', models.DateTimeField(auto_now=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user')),
            ],
        ),
        migrations.AlterField(
            model_name='usersingroup',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.group'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.comment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user')),
            ],
        ),
    ]
