# Generated by Django 4.0.1 on 2022-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_comment_alter_usersingroup_groupid_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='groupid',
            field=models.CharField(default='NULL', max_length=512),
        ),
    ]
